# Generated by Selenium IDE
import os
import pytest
import time
import json
import configparser
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import Select

class WebProCategory():
  def setupMethod(self):
    # get parent directory
    runTest.workDir = os.getcwd()
    # read config.ini
    path = self.workDir + "\Config"
    self.config = configparser.ConfigParser()
    self.config.read(os.path.join(path, 'config.ini'))

  def tearUpMethod(self):
    service = Service(self.workDir + '\Bin\chromedriver.exe')
    self.driver = webdriver.Chrome(service = service)
    self.driver.maximize_window()
    self.vars = {}
  
  def tearDownMethod(self):
    self.driver.quit()
  
  def webProCategory(self):
    webpro_username = self.config['WEBPRO']['username']
    webpro_password = self.config['WEBPRO']['password']
    webpro_url = self.config['WEBPRO']['webProUrl']
    wait = self.config['WEBPRO']['timewait']
    
    self.driver.get(webpro_url)
    self.driver.find_element(By.ID, "maintainer").click()
    self.driver.find_element(By.ID, "maintainer").send_keys(webpro_username)
    self.driver.find_element(By.ID, "pw").click()
    self.driver.find_element(By.ID, "pw").send_keys(webpro_password)
    self.driver.find_element(By.NAME, "bv:act_OK").click()

    element = self.driver.find_element(By.ID, "menu_item_account")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "menu_item_account").click()

    # Account Management and its subcategory
    self.driver.find_element(By.LINK_TEXT, "Category List").click()
    self.driver.find_element(By.NAME, "bv:act_Create").click()
    self.driver.find_element(By.ID, "moduleID").click()
    self.driver.find_element(By.ID, "moduleID").send_keys("account-management")
    self.driver.find_element(By.ID, "moduleName").click()
    self.driver.find_element(By.ID, "moduleName").send_keys("Account Management")
    self.driver.find_element(By.ID, "adminName").click()
    self.driver.find_element(By.ID, "adminName").send_keys("Account Management")
    select = Select(WebDriverWait(self.driver, wait).until(expected_conditions.element_to_be_clickable((By.ID, "client_source"))))
    select.select_by_visible_text("Template - Knowledge Category")
    self.driver.find_element(By.NAME, "bv:act_OK").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(2) span").click()
    self.driver.find_element(By.LINK_TEXT, "Subcategories").click()
    self.driver.find_element(By.ID, "topiclist-topicID").click()
    self.driver.find_element(By.ID, "topiclist-topicID").send_keys("change-details")
    self.driver.find_element(By.ID, "topiclist-topicName").click()
    self.driver.find_element(By.ID, "topiclist-topicName").send_keys("Change Details")
    self.driver.find_element(By.ID, "topiclist-topicAdminName").click()
    self.driver.find_element(By.ID, "topiclist-topicAdminName").send_keys("Change Details")
    self.driver.find_element(By.NAME, "bv:act_OK").click()
    self.driver.find_element(By.ID, "topiclist-topicID").click()
    self.driver.find_element(By.ID, "topiclist-topicID").send_keys("change-pin")
    self.driver.find_element(By.ID, "topiclist-topicName").click()
    self.driver.find_element(By.ID, "topiclist-topicName").send_keys("Change PIN")
    self.driver.find_element(By.ID, "topiclist-topicAdminName").click()
    self.driver.find_element(By.ID, "topiclist-topicAdminName").send_keys("Change PIN")
    self.driver.find_element(By.NAME, "bv:act_OK").click()
    self.driver.find_element(By.ID, "topiclist-topicID").click()
    self.driver.find_element(By.ID, "topiclist-topicID").send_keys("lost-stolen")
    self.driver.find_element(By.ID, "topiclist-topicName").click()
    self.driver.find_element(By.ID, "topiclist-topicName").send_keys("Replacement, Lost / Stolen")
    self.driver.find_element(By.ID, "topiclist-topicAdminName").click()
    self.driver.find_element(By.ID, "topiclist-topicAdminName").send_keys("Replacement, Lost / Stolen")
    self.driver.find_element(By.NAME, "bv:act_OK").click()
    self.driver.find_element(By.ID, "topiclist-topicID").click()
    self.driver.find_element(By.ID, "topiclist-topicID").send_keys("lost-stolen/lost")
    self.driver.find_element(By.ID, "topiclist-topicName").click()
    self.driver.find_element(By.ID, "topiclist-topicName").send_keys("Lost")
    self.driver.find_element(By.ID, "topiclist-topicAdminName").click()
    self.driver.find_element(By.ID, "topiclist-topicAdminName").send_keys("Lost")
    self.driver.find_element(By.NAME, "bv:act_OK").click()
    self.driver.find_element(By.ID, "topiclist-topicID").click()
    self.driver.find_element(By.ID, "topiclist-topicID").send_keys("lost-stolen/replacement")
    self.driver.find_element(By.ID, "topiclist-topicName").click()
    self.driver.find_element(By.ID, "topiclist-topicName").send_keys("Replacement")
    self.driver.find_element(By.ID, "topiclist-topicAdminName").click()
    self.driver.find_element(By.ID, "topiclist-topicAdminName").send_keys("Replacement")
    self.driver.find_element(By.NAME, "bv:act_OK").click()
    self.driver.find_element(By.ID, "topiclist-topicID").click()
    self.driver.find_element(By.ID, "topiclist-topicID").send_keys("online-login")
    self.driver.find_element(By.ID, "topiclist-topicName").click()
    self.driver.find_element(By.ID, "topiclist-topicName").send_keys("Online Login")
    self.driver.find_element(By.ID, "topiclist-topicAdminName").click()
    self.driver.find_element(By.ID, "topiclist-topicAdminName").send_keys("Online Login")
    self.driver.find_element(By.NAME, "bv:act_OK").click()

    # Credit Card
    self.driver.find_element(By.LINK_TEXT, "Category List").click()
    self.driver.find_element(By.NAME, "bv:act_Create").click()
    self.driver.find_element(By.ID, "moduleID").click()
    self.driver.find_element(By.ID, "moduleID").send_keys("credit-card")
    self.driver.find_element(By.ID, "moduleName").click()
    self.driver.find_element(By.ID, "moduleName").send_keys("Credit Card")
    self.driver.find_element(By.ID, "adminName").click()
    self.driver.find_element(By.ID, "adminName").send_keys("Credit Card")
    select = Select(WebDriverWait(self.driver, wait).until(expected_conditions.element_to_be_clickable((By.ID, "client_source"))))
    select.select_by_visible_text("Template - Knowledge Category")
    self.driver.find_element(By.NAME, "bv:act_OK").click()

    # Lending
    self.driver.find_element(By.NAME, "bv:act_Create").click()
    self.driver.find_element(By.ID, "moduleID").click()
    self.driver.find_element(By.ID, "moduleID").send_keys("lending")
    self.driver.find_element(By.ID, "moduleName").click()
    self.driver.find_element(By.ID, "moduleName").send_keys("Lending")
    self.driver.find_element(By.ID, "adminName").click()
    self.driver.find_element(By.ID, "adminName").send_keys("Lending")
    select = Select(WebDriverWait(self.driver, wait).until(expected_conditions.element_to_be_clickable((By.ID, "client_source"))))
    select.select_by_visible_text("Template - Knowledge Category")
    self.driver.find_element(By.NAME, "bv:act_OK").click()

    # Mortgages
    self.driver.find_element(By.NAME, "bv:act_Create").click()
    self.driver.find_element(By.ID, "moduleID").click()
    self.driver.find_element(By.ID, "moduleID").send_keys("mortgages")
    self.driver.find_element(By.ID, "moduleName").click()
    self.driver.find_element(By.ID, "moduleName").send_keys("Mortgages")
    self.driver.find_element(By.ID, "adminName").click()
    self.driver.find_element(By.ID, "adminName").send_keys("Mortgages")
    select = Select(WebDriverWait(self.driver, wait).until(expected_conditions.element_to_be_clickable((By.ID, "client_source"))))
    select.select_by_visible_text("Template - Knowledge Category")
    self.driver.find_element(By.NAME, "bv:act_OK").click()

    # Pension
    self.driver.find_element(By.NAME, "bv:act_Create").click()
    self.driver.find_element(By.ID, "moduleID").click()
    self.driver.find_element(By.ID, "moduleID").send_keys("pension")
    self.driver.find_element(By.ID, "moduleName").click()
    self.driver.find_element(By.ID, "moduleName").send_keys("Pension")
    self.driver.find_element(By.ID, "adminName").click()
    self.driver.find_element(By.ID, "adminName").send_keys("Pension")
    select = Select(WebDriverWait(self.driver, wait).until(expected_conditions.element_to_be_clickable((By.ID, "client_source"))))
    select.select_by_visible_text("Template - Knowledge Category")
    self.driver.find_element(By.NAME, "bv:act_OK").click()

    # Insurance
    self.driver.find_element(By.NAME, "bv:act_Create").click()
    self.driver.find_element(By.ID, "moduleID").click()
    self.driver.find_element(By.ID, "moduleID").send_keys("insurance")
    self.driver.find_element(By.ID, "moduleName").click()
    self.driver.find_element(By.ID, "moduleName").send_keys("Insurance")
    self.driver.find_element(By.ID, "adminName").click()
    self.driver.find_element(By.ID, "adminName").send_keys("Insurance")
    select = Select(WebDriverWait(self.driver, wait).until(expected_conditions.element_to_be_clickable((By.ID, "client_source"))))
    select.select_by_visible_text("Template - Knowledge Category")
    self.driver.find_element(By.NAME, "bv:act_OK").click()

    # Savings
    self.driver.find_element(By.NAME, "bv:act_Create").click()
    self.driver.find_element(By.ID, "moduleID").click()
    self.driver.find_element(By.ID, "moduleID").send_keys("saving")
    self.driver.find_element(By.ID, "moduleName").click()
    self.driver.find_element(By.ID, "moduleName").send_keys("Savings")
    self.driver.find_element(By.ID, "adminName").click()
    self.driver.find_element(By.ID, "adminName").send_keys("Savings")
    select = Select(WebDriverWait(self.driver, wait).until(expected_conditions.element_to_be_clickable((By.ID, "client_source"))))
    select.select_by_visible_text("Template - Knowledge Category")
    self.driver.find_element(By.NAME, "bv:act_OK").click()
  
if __name__ == '__main__':
  print("Hi python")
  runTest = WebProCategory()
  runTest.setupMethod()
  runTest.tearUpMethod()
  runTest.webProCategory()
  runTest.tearDownMethod()